name: Make and host Doxygen docs

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: apt-get install -y doxygen graphviz ttf-freefont
        
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build Docs
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release --target XMLBuilderLib_Docs

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "${{ steps.strings.outputs.build-output-dir }}/docs/html"
        publish_branch: lib-docs
