name: Make and host Doxygen docs

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
        
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build Docs
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: "${{ steps.strings.outputs.build-output-dir }}/docs"
        doxyfile-path: "${{ steps.strings.outputs.build-output-dir }}/docs/Doxyfile"

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "${{ steps.strings.outputs.build-output-dir }}/docs/html"
        publish_branch: lib-docs
